# Generated by Django 4.1.3 on 2023-01-09 19:10

from django.db import migrations

def create_coordinate1(apps, schema_editor):
    NewCoordinate = apps.get_model('restaurateur', 'OrderCoordinate1')
    OldCoordinate = apps.get_model('foodcartapp', 'OrderCoordinate')
    for coordinate in OldCoordinate.objects.all().iterator():
        NewCoordinate.objects.get_or_create(address=coordinate.address,
                                    lng=coordinate.lng,
                                    lat=coordinate.lat,
                                    )


class Migration(migrations.Migration):

    dependencies = [
        ('restaurateur', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_coordinate1)
    ]
