# Generated by Django 4.1.7 on 2023-04-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurateur', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderCoordinate1',
            new_name='OrderCoordinate',
        ),
        migrations.AlterModelOptions(
            name='ordercoordinate',
            options={'verbose_name': 'координаты', 'verbose_name_plural': 'координаты'},
        ),
        migrations.AlterModelTable(
            name='ordercoordinate',
            table='coordinate',
        ),
    ]
