# Generated by Django 4.1.3 on 2023-01-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurateur', '0002_auto_20230109_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderCoordinate1',
            new_name='OrderCoordinate',
        ),
        migrations.AlterModelOptions(
            name='ordercoordinate',
            options={'verbose_name': 'координаты', 'verbose_name_plural': 'координаты'},
        ),
        migrations.AlterModelTable(
            name='ordercoordinate',
            table='coordinate',
        ),
    ]
