# Generated by Django 4.1.3 on 2022-12-05 18:36

from django.db import migrations

def filling_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')

    for orderitem in OrderItem.objects.all().iterator():
        price = orderitem.product.price
        orderitem.price = price
        orderitem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitem_price'),
    ]

    operations = [migrations.RunPython(filling_price)
    ]
