# Generated by Django 4.1.3 on 2022-12-08 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20221205_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('New', 'Необработанный'), ('Process', 'Собираем'), ('Go', 'Доставка'), ('Done', 'Выполнен')], db_index=True, default='New', max_length=7, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена в заказе'),
        ),
    ]
