# Generated by Django 4.1.3 on 2022-12-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_status_order_alter_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status_order',
            new_name='order_status',
        ),
    ]
