# Generated by Django 4.1.3 on 2022-12-09 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='дата звонка'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='registrated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания заказа'),
        ),
    ]
