# Generated by Django 4.1.3 on 2022-12-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_called_order_delivered_order_registrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Right_now', (('cash', 'Наличностью'), ('by_card', 'Электронно'))), ('Delivery_pay', (('cash', 'Наличностью'), ('by_card', 'Электронно')))], db_index=True, default='Delivery_pay', max_length=50, verbose_name='статус заказа'),
        ),
    ]
