# Generated by Django 4.1.3 on 2022-12-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Right_now', 'Оплатить сейчас'), ('Delivery_pay', (('cash', 'Наличностью при доставке'), ('by_card', 'Электронно при доставке')))], db_index=True, default='Delivery_pay', max_length=10, verbose_name='статус заказа'),
        ),
    ]
