# Generated by Django 4.1.3 on 2022-12-10 09:20

from django.db import migrations

def filling_payment(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    for order in Order.objects.all().iterator():
        RIGHT_NOW = 'right_now'
        DELIVERY_CASH = 'delivery_pay_cash'
        DELIVERY_CARD = 'delivery_pay_card'

        PAYMENT = (
            (RIGHT_NOW, 'Оплатить сейчас'),
            (DELIVERY_CASH, 'Наличностью при доставке'),
            (DELIVERY_CARD, 'Электронно при доставке'),
        )
        order.payment = DELIVERY_CASH
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_payment'),
    ]

    operations = [migrations.RunPython(filling_payment)
    ]
