# Generated by Django 4.1.3 on 2022-12-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_coordinate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinate',
            options={'verbose_name': 'координаты', 'verbose_name_plural': 'координаты'},
        ),
        migrations.AlterModelTable(
            name='coordinate',
            table='coordinate',
        ),
    ]
