# Generated by Django 4.1.3 on 2022-12-27 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_order_called_alter_order_delivered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordinate',
            new_name='OrderCoordinate',
        ),
    ]
