# Generated by Django 4.1.3 on 2022-12-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_rename_coordinate_ordercoordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercoordinate',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='адрес места'),
        ),
        migrations.AlterField(
            model_name='ordercoordinate',
            name='lat',
            field=models.FloatField(blank=True, verbose_name='Широта/Latitude'),
        ),
        migrations.AlterField(
            model_name='ordercoordinate',
            name='lng',
            field=models.FloatField(blank=True, verbose_name='Долгота/Longitude'),
        ),
    ]
