# Generated by Django 4.1.3 on 2022-12-28 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_remove_order_restaurant_order_order_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='called',
            new_name='called_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivered',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='registrated',
            new_name='registrated_at',
        ),
    ]
