# Generated by Django 4.1.3 on 2022-12-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_remove_order_payment_order_method_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий к заказу'),
        ),
    ]
