# Generated by Django 4.1.3 on 2023-01-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0064_alter_order_comment'),
    ]

    operations = [migrations.DeleteModel(
            name='OrderCoordinate',
        ),
    ]
