# Generated by Django 4.1.3 on 2023-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0068_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('raw_order', 'Необработанный'), ('collecting_order', 'Собираем'), ('go', 'Доставка'), ('done', 'Выполнен')], db_index=True, default='raw_order', max_length=17, verbose_name='статус заказа'),
        ),
    ]
