# Generated by Django 4.1.3 on 2023-01-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0070_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant_order',
            new_name='restaurant_for_order',
        ),
    ]
