# Generated by Django 4.1.3 on 2023-01-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0071_rename_restaurant_order_order_restaurant_for_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, verbose_name='адрес'),
        ),
    ]
